### PR TITLE
Addition of collapsible sections, keywords cloud, switch, levels, and glossary page

### PR DESCRIPTION
**Pull request by PierreDillard**
#### Addition of Glossary Tab

**Before:**

The documentation did not have a Glossary tab.  
Before Glossary

**After:**

A new Glossary tab has been added to the navigation menu (in development).  
After Glossary

#### Keywords Cloud

**Before:**

No keywords cloud was available.  
Before Keywords Cloud

**After:**

A dynamic keywords cloud is displayed based on a `keywords.json` file. Keywords are shown according to the page visited (most common technical terms on the page (>2 and contained in the lexicon)). Clicking on a keyword opens a modal window with the definition and a "Read more" link redirects to the "keyword/glossary" page.  
After Keywords Cloud (completed, but final lexicon still needed)

#### Collapsible Sections

**Before:**

Sections were not collapsible, making navigation more difficult.  
Before Collapsible Sections

**After:**

Main titles (H2) are now in collapsible menus, allowing better visibility and quicker access to information.  
After Collapsible Sections (completed for all H2 on the page)

#### Expertise Level Selector

**Before:**

No selector to choose the expertise level.  
Before Expertise Level Selector

**After:**

Added a selector at the top left to choose the expertise level (expert or beginner). Keywords and sections displayed change based on the selected level ("Expert/Beginner").  (Howtos/filters-oneliners & Howtos/inspecting)
After Expertise Level Selector (completed)

#### Tags on Collapsible Sections

Added an attribute directly to the markdown next to the H1 (in markdown) `{: data-level="beginner" }` for the "beginner" level (completed, levels yet to be chosen).  

Created an "all" attribute that will be displayed regardless of the selected menu "beginner" or "expert" and will be expanded by default (e.g., "overview", "foreword" sections).

#### Modal Feature for Keywords

Modal feature on keyword click, displaying the definition and a "Read more" link redirecting to the keyword page. For testing, created the `glossary/encode` and `glossary/encrypt` pages.

#### Scroll to Top Navigation

**Before:**

No button to quickly return to the top of the page.  
Before Scroll to Top

**After:**

Added an icon button that appears after scrolling, allowing immediate navigation to the top of the page.  
After Scroll to Top (completed)

### Additional Information

Using a dynamic URL for the JavaScript bundle caused several features to malfunction, such as the search bar and the scroll-to-top button (only in development mode via `mkdocs serve`).  
Using `<script src="{{ 'assets/javascripts/bundle.fe8b6f2b.min.js' | url }}"></script>` to fix the issue.

### To Do

- Create the final lexicon
- Create all glossary pages

### CODE REVIEW

**Comment by PierreDillard** [comment]
Hello  @nlsdvl or @rbouqueau,  could you please review this PR? Thanks!

**Comment by nlsdvl** [comment]
@PierreDillard The PR is marked as 'draft', did you mean to submit it for review for validation before merging ? or are you just looking forward to feedback at this point ?

**Comment by PierreDillard** [comment]
> @PierreDillard The PR is marked as 'draft', did you mean to submit it for review for validation before merging ? or are you just looking forward to feedback at this point ?

Hi @nlsdvl,

 Indeed, the PR is currently marked as "draft". Here is a status update on the functionalities:
 
### Completed functionalities:
- **Menu collapse**
- **Top navigation**
- **Switch (TOC/NAV) on the left**: implemented to make room for the keywords cloud
- **Levels (experts-beginner-all)** are functional, but the sections concerned still need to be selected in the DOC (adding attributes in the Markdown)

### Functionalities under development:

- **Keywords clouds**: still needs to be implemented with a complete lexicon of keywords and adapted according to levels (experts-beginner-all)
- **Pages for keywords**: The pages for keywords such as "encode" and "encrypt" are available for testing, but the rest are still in progress.
- **Glossary tab**: A new tab for "Glossary" will appear in the navigation once the lexicon and all the keyword pages are completed.

For now, I would like to get feedback on the completed functionalities to validate them. Regarding the functionalities under development, I am open to suggestions or feedback that could improve their integration.
So, if possible, could you please give me your feedback on the functionalities already in progress?

**Comment by PierreDillard** [comment]
Hi Nils, I've commented on all ongoing development features (keywords links to glossary pages,glossary tabs in yaml )

**Review by nlsdvl — CHANGES_REQUESTED** [review]
@PierreDillard thanks for submitting this contribution. Sorry for the late feedback, I just couldn't find the bandwidth to handle it in the past 2 weeks. I see that you committed more changes since, so you get the feedback on your latest commits. There are several issues that led me to reject the PR in its current state, more details below.

We've deployed your work to [dev.wiki.gpac.io](http://dev.wiki.gpac.io) so that you can collect feedback more conveniently. I'll get back to you on how to keep it updated.


### Glossary tab / Keywords Cloud

- The glossary tab doesn’t show up in expert mode, is that expected ?
- Dark mode styling missing
- Is this compatible with tags : https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/ ?


### Back to top

- dark mode styling missing

### Beginner / Expert mode

I’m not sure I understand the motivation for this change. What is considered expert, what is considered beginner ? This is quite opinionated, what are the guidelines on this ? As a beginner you should be encouraged to ramp up, this is editorial work - just personal opinion here. I any case, I don’t think we should merge into the main branch until the content tagging has been entirely curated. I look forward to discuss this further during the next call we have on schedule with all those involved and interested in this.

- The expert mode switch needs to be better located, eg. next to the dark mode switch. It actually took me some time to find it.
- The left sidebar menu is not treated consistently with the content. Expert content is listed in the menu even when it’s disabled.
- Can you clarify how the content tagging and related switch work ? This also needs to be documented. It seems content that is not explicitly tagged is hidden away when the switch is on ‘beginner’ and as a result is that the whole documentation is filtered out by default in your PR. The opposite behavior would be preferable IMHO: show me everything, let me filter out what is too much for me. In that case the ‘all’ option doesn’t make much sense. Did I misunderstand your intention ?
- There seems to be a bug with this feature, eg. exhibiting on the /Filters/avmix page
- The search feature becomes deceptive with this change: search for content that is in expert mode, while you are in beginner mode, when you click to display the result, nothing shows up.

### Collapsible content

- dark mode styling missing
- Everything is collapsed by default. Please get feedback from other users on this. I personally tend to prefer using collapsible sparingly, but the TOC is now hidden by default so I guess it gives an overview of the page’s content without having to scroll through.
- The styling changes added extra spaces between the title and the permalink button.
- On desktop Safari browser, the first line of the collapsed block is still visible.


### Switch (TOC/NAV) on the left: implemented to make room for the keywords cloud

- I took me a moment to understand what this was doing when I started testing your branch. At first I was like I was like where’s the TOC ? If you keep this behavior, make sure to emphasize the menu’s title (eg. ‘MP4Box’) and Table of content more. It would help to understand what clicking on that button does before clicking on it. 
- When you hide the menu because you want to have the TOC, you need to switch back to the menu mode to navigate around the wiki. 


### Git related feedback
- Avoid force push to your branch as much as you can, at all cost if you are sharing the branch with someone else.
- There’s something wrong with the git config here that we need to work out. You have thousands of files modified in your branch. Most likely something we can resolve with proper git repo configuration, eg. .gitattribute.

cc @rbouqueau @jeanlf

**Pull request closed without merging**
