### PR TITLE
Wiki updates

### PR DESCRIPTION
**Pull request by PierreDillard**
# Response to Feedback

Thank you for your detailed feedback. 

## Glossary tab / Keywords Cloud

* **The glossary tab doesn't show up in expert mode, is that expected?**
  - The glossary tab is currently not displaying in either "expert" or "beginner" mode. This feature is still under development and will be implemented in a future update.

* **Dark mode styling missing**
  - Dark mode styling has been addressed for collapses, keywords cloud, top navigation, and toggle button. Some updates may not be visible on dev.wiki.gpac.io as modifications were made to /overrides files outside of /doc.

* **Is this compatible with tags?**
  - Yes, it's compatible with tags. We could potentially use tags for glossary pages to make them easier to find.

## Back to top

* **Dark mode styling missing**
  - Dark mode styling has been implemented for this feature.

## Beginner / Expert mode

* **Motivation for this change**
  - The focus has been primarily on the "howtos" section. The intention is to allow new users to quickly access essential information.
  - Detailed categorization will be discussed further with Jean.

* **Expert mode switch location**
  - The expert mode switch location has been changed to be next to the dark mode icon, although this isn't visible on dev.wiki.gpac.io due to /overrides modifications.

* **Content tagging and related switch**
  - A new document, "content-tagging-system.md", has been created at the project root to detail the tagging system's functionality.
  - The default behavior has been rectified to "expert" mode, showing everything by default.

* **Bug on /Filters/avmix page**
  - This has been documented in content-tagging-system.md. It's a formatting issue when there's a code block in the markdown. The solution is to add a line break between the code block and the following line. Some pages have been fixed, but others still need attention.

* **Search feature issue**
  - A tooltip has been added to inform users that switching to expert mode is better for searching.

## Collapsible content

* **Dark mode styling**
  - Dark mode styling has been implemented.

* **Default collapsed state**
  - The decision to collapse everything by default was made for better readability. However, this functionality could be limited to specific sections if it's too disruptive.

* **Spacing issue**
  - The spacing issue between the title and the permalink button has been fixed.

* **Safari desktop issue**
  - The issue couldn't be reproduced. More information about specific pages where this occurs would be helpful.

## Switch (TOC/NAV) on the left

* **Reason for change**
  - This change was primarily made to accommodate the keyword cloud.

* **User understanding**
  - The icon has been changed and a tooltip added to inform users about the ability to switch between TOC and nav. These changes are not yet visible on dev.wiki.gpac.io due to needed /overrides modifications.

## Git related feedback

* **Force push and file modifications**
  - The git issues have been resolved by starting with a new branch.

### CODE REVIEW

**Review by k757657 — APPROVED** [review]

**Review by k757657 — APPROVED** [review]

**Comment by PierreDillard** [comment]
### Main Updates:

- Restored the Table of Contents (TOC) on the right side of the page.
image

- All collapsed menus are now opened by default.
- Added a new "Settings" menu in the header to allow users to personalize their experience:
  - **Expert/Beginner option:** By default, the experience is set to "Expert."
  - **Collapse menus:** Menus are expanded by default.
  - **Dark mode settings.**

Capture d’écran du 2024-09-23 15-36-16

- In the Filters and MP4 box :
  - In **Expert mode**, all filter options are visible.
  - In **Beginner mode**, only the "basic" options are displayed.

**Comment by PierreDillard** [comment]
Hey @nlsdvl,

I hope you're doing well! When you have a moment, could you please review the updates in this PR? I've restored the Table of Contents, adjusted the menu settings, and added a few customization options. Any feedback would be greatly appreciated  !

**Comment by jeanlf** [comment]
when merging this, we'll have to merge https://github.com/gpac/gpac/tree/buildbot-hintclass

**Comment by nlsdvl** [comment]
@jeanlf - I would like to merge this. 

I assume the Filter's documentation was generated from that branch : https://github.com/gpac/gpac/tree/buildbot-hintclass 

I've opened a PR with the changes in gpac supporting this wiki update: https://github.com/gpac/gpac/pull/3025/ 
We need to merge it before #7 can be automated.

@PierreDillard - thanks for all the work one this and taking into account everybody's feedback.

**Comment by jeanlf** [comment]
@nlsdvl could you rebase first ?  I'll merge everything once done

**Review by jeanlf — APPROVED** [review]

**Comment by jeanlf** [comment]
all merged !

**Pull request merged**
